# Secret used by ArgoCD Notifications to store sensitive credentials
# such as email username and password.

apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd

type: Opaque

stringData:
  email-username: "<email-username>"
  email-password: "<email-app-password>"
