apiVersion: apps/v1
kind: Deployment
metadata:
  name: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student
        image: shubhamm18/webapp:03
        ports:
        - containerPort: 3000
