apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd

data:
  policy.csv: |
    # ---------------------------
    # Roles
    # ---------------------------

    # Admin → full access
    
    p, role:admin, applications, *, */*, allow

    # Read-only → only view apps
    p, role:readonly, applications, get, */*, allow

    # Developer → can view and deploy
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, sync, */*, allow

    # ---------------------------
    # User to Role Mapping
    # ---------------------------

    g, shubham, role:admin
    g, alex, role:readonly
    g, gulshankumar, role:developer

  # Default role
  policy.default: role:readonly
