apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd

data:
  url: http://localhost:8080

  # =========================
  # USERS
  # =========================

  accounts.shubham: apiKey, login
  accounts.alex: login
  accounts.gulshankumar: apiKey

  # Default fallback role
  policy.default: role:readonly
