apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd

data:
  # ArgoCD server URL
  url: http://localhost:8080

  # =========================
  # LOCAL USER ACCOUNTS
  # =========================

  # login  → UI access
  # apiKey → token (CI/CD)

  accounts.alice: apiKey, login
  accounts.bob: login
  accounts.ci-user: apiKey

  # Default role fallback
  policy.default: role:readonly
