apiVersion: argoproj.io/v2alpha1
kind: Application
metadata:
  name: portfolio-frontend
  namespace: argocd
spec:
  project: frontend-project
  source:
    repoURL: https://github.com/Shubhamx18/argocd-gitops.git
    targetRevision: main
    path: practicals/portfolio-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
~
